debug: true

server:
  port: 8888

zuul:
  routes:
    geo-service:
      path: /geo/**
      url: http://localhost:9090

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
